# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHcxcPeGGEGLRJ0iYfeM4r9sl76gPpvV

Vidushi Mittal

M25MAC014

NLU-A2

## PROBLEM 1: LEARNING WORD EMBEDDINGS FROM IIT JODHPUR DATA

Importing the required libraries.
"""

import re
import nltk
import numpy as np
from nltk.tokenize import word_tokenize
from collections import Counter
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import requests
from bs4 import BeautifulSoup
import time

"""TASK-1: DATASET PREPARATION"""

# Download required NLTK data
nltk.download('punkt')
nltk.download('punkt_tab')

def preprocess_text(raw_text):
    """
    Cleaning the raw text collected from IIT Jodhpur sources.
    """
    # 1. Lowercasing
    text = raw_text.lower()

    # 2. Remove boilerplate, excessive punctuation, and non-textual content using Regex
    # This keeps only alphabetical characters and spaces
    text = re.sub(r'[^a-z\s]', ' ', text)
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)

    # Remove newlines and extra spaces
    text = text.replace('\n', ' ')
    # Remove multiple spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # 3. Tokenization
    tokens = word_tokenize(text)

    # Remove very short tokens or specific stop words if needed
    clean_tokens = [word for word in tokens if len(word) > 1]

    return clean_tokens

def generate_dataset_stats(clean_tokens):
    """
    Calculates vocabulary size and plots the Word Cloud.
    """
    # 1. Calculate Statistics
    total_tokens = len(clean_tokens)
    vocab = set(clean_tokens)
    vocab_size = len(vocab)

    print(f"Total number of tokens: {len(clean_tokens)}")
    print(f"Vocabulary size: {len(vocab)}")

    # Generating Word Cloud
    word_freq = Counter(clean_tokens)
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate_from_frequencies(word_freq)

    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.title("Most Frequent Words in IIT Jodhpur Corpus")
    plt.show()

    # Save the cloud for report
    wordcloud.to_file("iitj_wordcloud.png")
    print("\nWord Cloud saved as 'iitj_wordcloud.png'")

import os

def save_corpus_to_file(text, filename="corpus.txt"):
    """
    Saves the processed string to a text file.
    """
    try:
        # using utf-8 encoding to ensure special characters don't crash the write process
        with open(filename, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"\nSuccessfully saved corpus to: {os.path.abspath(filename)}")
    except Exception as e:
        print(f"Error saving file: {e}")

!pip install PyMuPDF
import fitz  # PyMuPDF
import io
from urllib.parse import urljoin

# providing the desired links
def scrape_iitj_with_pdfs():
    target_urls = [
        "https://www.iitj.ac.in/", # Home and Announcements
        "https://www.iitj.ac.in/m/Index/main-departments?lg=en", # Departments
        "https://www.iitj.ac.in/office-of-academics/en/academic-programs", # Academic Programs
        "https://www.iitj.ac.in/office-of-research-development/en/office-of-research-and-development" ,# Research Pages,
        "https://www.iitj.ac.in/office-of-research-development/en/information" # Reserach info
    ]


    # Using a User-Agent header so the university server recognizes this as a standard browser request, rather than blocking it as an automated bot.
    headers = {'User-Agent': 'Mozilla/5.0'}
    full_corpus = ""

    for url in target_urls:
        print(f"--- Processing Page: {url} ---")
        try:
            response = requests.get(url, headers=headers, timeout=15)
            if response.status_code != 200: continue

            soup = BeautifulSoup(response.text, 'html.parser')

            # A. Extract Text from the HTML Page first
            for element in soup.find_all(['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'li']):
                full_corpus += element.get_text(strip=True) + " "

            # B. Find all PDF links
            pdf_links = []
            for link in soup.find_all('a', href=True):
                href = link['href']
                if href.lower().endswith('.pdf'):
                    # Convert relative URL to absolute URL
                    pdf_url = urljoin(url, href)
                    pdf_links.append(pdf_url)

            # C. Scrape each PDF found
            for pdf_url in set(pdf_links): # 'set' removes duplicates
                print(f"   -> Extracting PDF: {pdf_url.split('/')[-1]}")
                try:
                    pdf_response = requests.get(pdf_url, headers=headers, timeout=20)
                    # Open PDF from bytes
                    with fitz.open(stream=io.BytesIO(pdf_response.content), filetype="pdf") as doc:
                        pdf_text = ""
                        for page in doc:
                            pdf_text += page.get_text()
                        full_corpus += pdf_text + " "
                except Exception as e:
                    print(f"      Error reading PDF {pdf_url}: {e}")

                time.sleep(0.5)

        except Exception as e:
            print(f"Error scraping {url}: {e}")

    return full_corpus

# Execution

print("Starting web scraper...")
corpus_data = scrape_iitj_with_pdfs()

if corpus_data.strip():
    print(f"\nScraping complete. Total characters collected: {len(corpus_data)}")
    print("\nPreprocessing text...")
    clean_corpus_tokens = preprocess_text(corpus_data)
    print("\nPreprocessing complete. Generating stats...")
    generate_dataset_stats(clean_corpus_tokens)
    # Saving the cleaned corpus as text file
    clean_corpus_tokens_string = " ".join(clean_corpus_tokens)
    save_corpus_to_file(clean_corpus_tokens_string, "corpus.txt")

else:
    print("No text was scraped. Please check your internet connection or the target URLs.")

"""TASK-2: MODEL TRAINING

Train two Word2Vec models: Continuous Bag of Words (CBOW) and Skip-gram with Negative
Sampling. For each model, experiment with: (i) Embedding dimension, (ii) Context window
size and (iii) Number of negative samples. Show these results formally in the report.
"""

# models from scratch

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

class Word2VecDataset(Dataset):
    def __init__(self, tokens, word_to_idx, window_size=2, mode='skipgram'):
        self.data = []
        self.mode = mode
        for i in range(window_size, len(tokens) - window_size):
            target = word_to_idx[tokens[i]]
            context = [word_to_idx[tokens[i-j]] for j in range(1, window_size+1)] + \
                      [word_to_idx[tokens[i+j]] for j in range(1, window_size+1)]

            if mode == 'skipgram':
                # Skip-gram: Each context word is a separate training example
                for ctx in context:
                    self.data.append((target, ctx))
            else:
                # CBOW: The entire context window predicts one target
                self.data.append((torch.tensor(context), target))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

class CBOWModel(nn.Module):
    def __init__(self, vocab_size, embed_dim):
        super(CBOWModel, self).__init__()
        self.embeddings = nn.Embedding(vocab_size, embed_dim)
        self.output = nn.Linear(embed_dim, vocab_size)

    def forward(self, context_ids):
        # context_ids shape: [batch_size, window_size*2]
        embeds = self.embeddings(context_ids) # [batch_size, window_size*2, embed_dim]
        avg_embeds = torch.mean(embeds, dim=1) # Average the context
        return self.output(avg_embeds)


class SkipGramModel(nn.Module):
    def __init__(self, vocab_size, embed_dim):
        super(SkipGramModel, self).__init__()
        self.embeddings = nn.Embedding(vocab_size, embed_dim)
        self.output = nn.Linear(embed_dim, vocab_size)

    def forward(self, target_id):
        v = self.embeddings(target_id)
        return self.output(v)

def train_model(tokens, mode='skipgram', embed_dim=100, epochs=10):
    vocab = sorted(list(set(tokens)))
    word_to_idx = {word: i for i, word in enumerate(vocab)}
    idx_to_word = {i: word for i, word in enumerate(vocab)}

    dataset = Word2VecDataset(tokens, word_to_idx, mode=mode)
    dataloader = DataLoader(dataset, batch_size=512, shuffle=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = SkipGramModel(len(vocab), embed_dim) if mode == 'skipgram' else CBOWModel(len(vocab), embed_dim)
    model.to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.005)

    print(f"\nTraining {mode.upper()} from scratch...")
    for epoch in range(epochs):
        total_loss = 0
        for x, y in dataloader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            output = model(x)
            loss = criterion(output, y)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        if (epoch + 1) % 2 == 0:
            print(f"Epoch {epoch+1} | Loss: {total_loss/len(dataloader):.4f}")

    return model, word_to_idx, idx_to_word

# EXECUTION
scratch_sg_model, w2i, i2w = train_model(clean_corpus_tokens, mode='skipgram')
scratch_cbow_model, _, _ = train_model(clean_corpus_tokens, mode='cbow')

# using inbuilt model libraries
!pip install gensim
from gensim.models import Word2Vec

def find_best_models(sentences):
    # Experiment Parameters as per Task-2 requirements
    dimensions = [50, 100, 200]      # (i) Embedding dimension
    windows = [2, 5, 10]             # (ii) Context window size
    neg_samples = [5, 15]            # (iii) Number of negative samples

    # Storage for the best versions
    best_cbow = {'model': None, 'score': -1, 'params': None}
    best_sg = {'model': None, 'score': -1, 'params': None}

    # using a random 'Validation Pair' to score the models
    # A good IITJ model should recognize that 'phd' and 'research' are related
    val_word_1, val_word_2 = 'phd', 'research'

    for sg_val in [0, 1]: # 0 = CBOW, 1 = Skip-gram
        arch_name = "CBOW" if sg_val == 0 else "Skip-gram"
        print(f"Optimizing {arch_name}...")

        for dim in dimensions:
            for win in windows:
                for neg in neg_samples:
                    start = time.time()
                    model = Word2Vec(
                        sentences=sentences,
                        sg=sg_val,
                        vector_size=dim,
                        window=win,
                        negative=neg,
                        min_count=2,
                        workers=4
                    )
                    duration = time.time() - start

                    try:
                        # Calculate cosine similarity score for this specific config
                        current_score = model.wv.similarity(val_word_1, val_word_2)
                    except KeyError:
                        current_score = 0

                    # displaying scores
                    print(f"{arch_name:<12} | {dim:<5} | {win:<5} | {neg:<5} | {duration:<20} | {current_score:<8.4f}")

                    # Update Best CBOW
                    if sg_val == 0 and current_score > best_cbow['score']:
                        best_cbow.update({'model': model, 'score': current_score,
                                        'params': (dim, win, neg)})

                    # Update Best Skip-gram
                    if sg_val == 1 and current_score > best_sg['score']:
                        best_sg.update({'model': model, 'score': current_score,
                                       'params': (dim, win, neg)})

    return best_cbow, best_sg

# --- EXECUTION ---
# tokens are split into "sentences" for better window context
chunk_size = 20
sentences = [clean_corpus_tokens[i:i + chunk_size] for i in range(0, len(clean_corpus_tokens), chunk_size)]

print("\n ----Formal Reporting (Table) ---")
print(f"\n{'Architecture':<12} | {'Dim':<5} | {'Win':<5} | {'Neg':<5} | {'Time (s)':<20} | {'Cosine Scores':<8}")
print("-" * 70)
cbow_winner, sg_winner = find_best_models(sentences)

print(f"\nBEST CBOW: Dim={cbow_winner['params'][0]}, Win={cbow_winner['params'][1]}, Neg={cbow_winner['params'][2]} (Score: {cbow_winner['score']:.4f})")
print(f"BEST SKIP-GRAM: Dim={sg_winner['params'][0]}, Win={sg_winner['params'][1]}, Neg={sg_winner['params'][2]} (Score: {sg_winner['score']:.4f})")

# models trained with best combination of parameters identified using the inbuilt libraries
# 1. CBOW Model
model_cbow = Word2Vec(sentences=sentences,
                        sg=0,
                        vector_size=100,
                        window=2,
                        negative=5,
                        min_count=2,
                        workers=4)

# 2. Skip-gram Model (sg=1)
model_sg = Word2Vec(sentences=sentences,
                        sg=1,
                        vector_size=200,
                        window=2,
                        negative=5,
                        min_count=2,
                        workers=4)

print("Models trained successfully.")

"""TASK-3: SEMANTIC ANALYSIS

"""

import torch.nn.functional as F

# cosine similarity function for inbuilt models
def analyze_word(word, model,model_name):
    print(f"\nTop 5 neighbors for '{word}' as per model {model_name}:")
    try:
        neighbors = model.wv.most_similar(word, topn=5)
        for w, score in neighbors:
            print(f"{w}: {score:.4f}")
    except KeyError:
        print(f"Word '{word}' not in vocabulary.")

# To Create Mappings
def create_vocab_mappings(tokens):
    """Creates the dictionaries needed to turn text into numbers."""
    vocab = sorted(list(set(tokens)))
    w2i = {word: i for i, word in enumerate(vocab)}
    i2w = {i: word for i, word in enumerate(vocab)}
    return w2i, i2w, len(vocab)

# Analysis for Scratch Models
def analyze_scratch(word, model,model_name, w2i, i2w, topn=5):
    """Manually calculates cosine similarity for PyTorch models."""
    print(f"\nTop 5 neighbors for '{word}' as per model {model_name}:")
    if word not in w2i:
        print(f"Word '{word}' not in vocabulary.")
        return

    model.eval() # Set to evaluation mode
    device = next(model.parameters()).device

    with torch.no_grad():
        # Get the vector for our target word
        target_idx = torch.tensor([w2i[word]]).to(device)
        target_vec = model.embeddings(target_idx) # [1, embed_dim]

        # Get all vectors in the embedding layer
        all_vecs = model.embeddings.weight # [vocab_size, embed_dim]

        # Calculate Cosine Similarity
        # F.cosine_similarity computes similarity between the target and every row in all_vecs
        sims = F.cosine_similarity(target_vec, all_vecs)

        # Get top indices
        scores, indices = torch.topk(sims, topn + 1)


        for i in range(1, len(indices)): # Start from 1 to skip the word itself
            neighbor_word = i2w[indices[i].item()]
            print(f" - {neighbor_word}: {scores[i].item():.4f}")

# Analogy for Scratch Models
def solve_analogy_scratch(w1, w2, w3, model, w2i, i2w):
    """Solves w1:w2 :: w3:? (e.g., ug:btech :: pg:?)"""
    if any(w not in w2i for w in [w1, w2, w3]):
        return "Missing words in vocab"

    model.eval()
    device = next(model.parameters()).device
    with torch.no_grad():
        v1 = model.embeddings(torch.tensor([w2i[w1]]).to(device))
        v2 = model.embeddings(torch.tensor([w2i[w2]]).to(device))
        v3 = model.embeddings(torch.tensor([w2i[w3]]).to(device))

        # The analogy math: target = btech - ug + pg
        target_vec = v2 - v1 + v3

        all_vecs = model.embeddings.weight
        sims = F.cosine_similarity(target_vec, all_vecs)

        _, indices = torch.topk(sims, 5)
        for idx in indices:
            word = i2w[idx.item()]
            if word not in [w1, w2, w3]: # Return the first word that isn't part of the question
                return word
    return "Analogy words not found in small corpus."

# --- EXECUTION ---

# Creating the mappings first
w2i, i2w, vocab_size = create_vocab_mappings(clean_corpus_tokens)

# Using your new analysis functions
target_words = ['research', 'student', 'phd', 'exam']

for word in target_words:
    # for inbuilt models
    analyze_word(word, model_cbow, "CBOW_Inbuilt")
    analyze_word(word, model_sg, "Skip-gram_Inbuilt")
    # for models from stractch
    analyze_scratch(word, scratch_sg_model, "Skip-gram_from_Scratch", w2i, i2w)
    analyze_scratch(word, scratch_cbow_model, "CBOW_from_Scratch", w2i, i2w)

# Analogy: UG : BTech :: PG : ?
# Formula: result = vector(BTech) - vector(UG) + vector(PG)
print("\n--- ANALOGY EXPERIMENT ---")
print("\nUG is to BTech as PG is to...(as per Skip-gram_Inbuilt)")
try:
    result = model_sg.wv.most_similar(positive=['btech', 'pg'], negative=['ug'], topn=1)
    print(f"Result: {result[0][0]}")
except Exception as e:
    print("Analogy words not found in small corpus.")

print("\nUG is to BTech as PG is to...(as per CBOW_Inbuilt)")
try:
    result = model_cbow.wv.most_similar(positive=['btech', 'pg'], negative=['ug'], topn=1)
    print(f"UG : BTech :: PG : {result[0][0]}")
except Exception as e:
    print("Analogy words not found in small corpus.")

print("\nUG is to BTech as PG is to...(as per CBOW_from_Scratch)")
result = solve_analogy_scratch('ug', 'btech', 'pg', scratch_cbow_model, w2i, i2w)
print(f"UG : BTech :: PG : {result}")

print("\nUG is to BTech as PG is to...(as per Skip-gram_from_Scratch)")
result = solve_analogy_scratch('ug', 'btech', 'pg', scratch_sg_model, w2i, i2w)
print(f"UG : BTech :: PG : {result}")

"""TASK-4: VISUALIZATION

"""

from sklearn.manifold import TSNE

def visualize_embeddings(model, w2i, selected_words, title="Word Embedding Clusters"):
    """
    Projects high-dimensional embeddings into 2D using t-SNE.
    """

    # 1. Extract vectors for the selected words
    vectors = []
    valid_words = []

    # Check if the model is a PyTorch model (Scratch)
    is_pytorch = isinstance(model, torch.nn.Module)

    for word in selected_words:
        try:
            if is_pytorch:
                # Logic for Scratch PyTorch models
                if word in w2i:
                    model.eval()
                    device = next(model.parameters()).device
                    idx = torch.tensor([w2i[word]]).to(device)
                    with torch.no_grad():
                        vec = model.embeddings(idx).cpu().numpy().flatten()
                    vectors.append(vec)
                    valid_words.append(word)
            else:
                # Logic for Inbuilt Gensim models
                if word in model.wv:
                    vectors.append(model.wv[word])
                    valid_words.append(word)
        except Exception as e:
            continue


    if len(vectors) < 2:
        print(f"Not enough words found in {title} to visualize.")
        return

    if not vectors:
        print("None of the selected words were found in the vocabulary.")
        return

    vectors = np.array(vectors)

    # 2. Run t-SNE
    # Perplexity should be smaller than the number of points
    tsne = TSNE(n_components=2, random_state=42, perplexity=min(5, len(valid_words)-1), init='pca', learning_rate='auto')
    low_dim_embeds = tsne.fit_transform(vectors)

    # 3. Plotting
    plt.figure(figsize=(10, 8))
    for i, word in enumerate(valid_words):
        x, y = low_dim_embeds[i, :]
        plt.scatter(x, y, marker='o', color='red')
        plt.annotate(word, (x, y), xytext=(5, 2), textcoords='offset points', fontsize=12)

    plt.title(title)
    plt.grid(True)
    plt.show()

# --- EXECUTION ---
# Group words into logical clusters to see if the model groups them
academic_cluster = ['btech', 'mtech', 'phd', 'ug', 'pg', 'student', 'professor', 'faculty', 'research', 'exam', 'semester', 'credits']

print("Visualizing Scratch Skip-gram Clusters...")
# using w2i from previous cell
visualize_embeddings(scratch_sg_model, w2i, academic_cluster, title="t-SNE: Scratch Skip-gram (IIT Jodhpur)")

print("Visualizing Scratch CBOW Clusters...")
visualize_embeddings(scratch_cbow_model, w2i, academic_cluster, title="t-SNE: Scratch CBOW (IIT Jodhpur)")

print("Visualizing Inbuilt Skip-gram Clusters...")
visualize_embeddings(model_sg, w2i, academic_cluster, title="t-SNE: Inbuilt Skip-gram (IIT Jodhpur)")

print("Visualizing Inbuilt CBOW Clusters...")
visualize_embeddings(model_cbow, w2i, academic_cluster, title="t-SNE: Inbuilt CBOW (IIT Jodhpur)")

import random
# using a random list of words for vizualization from courpus
# Converting the corpus into a list of unique words (Vocabulary)
unique_vocab = list(set(clean_corpus_tokens))

# Ensure we don't try to sample more than what exists
# selecting random 40 words
sample_size = min(40, len(unique_vocab))
random_40_words = random.sample(unique_vocab, sample_size)
random_40_words

print("Visualizing Scratch Skip-gram Clusters...")
# using w2i from previous cell
visualize_embeddings(scratch_sg_model, w2i, random_40_words, title="t-SNE: Scratch Skip-gram (IIT Jodhpur)")

print("Visualizing Scratch CBOW Clusters...")
visualize_embeddings(scratch_cbow_model, w2i, random_40_words, title="t-SNE: Scratch CBOW (IIT Jodhpur)")

print("Visualizing Inbuilt Skip-gram Clusters...")
visualize_embeddings(model_sg, w2i, random_40_words, title="t-SNE: Inbuilt Skip-gram (IIT Jodhpur)")

print("Visualizing Inbuilt CBOW Clusters...")
visualize_embeddings(model_cbow, w2i, random_40_words, title="t-SNE: Inbuilt CBOW (IIT Jodhpur)")

"""QUESTION FROM GOOGLE FORM :
P1: Take one word from your learned vocabulary, for example  if you take “Jodhpur”, and print its full 300-dimensional embedding vector from your trained word2vec model on the IITJ corpus, as a comma-separated list. (Note: you should take a word of your choice other than Jodhpur). So the expected format is something like:

Jodhpur - 0.1284, -0.0921, 0.4410, ..., 0.0037
"""

# a prominent word from the IITJ corpus (other than Jodhpur)
target_word = "research"

# Check if the word exists in the  model's vocabulary
if target_word in model_cbow.wv:
    # Extract the full embedding vector (300 dimensions)
    vector = model_cbow.wv[target_word]

    # Format the vector values to 4 decimal places and join with commas
    formatted_vector = ", ".join([f"{val:.4f}" for val in vector])

    # Print in the exact requested format
    print(f"{target_word} - {formatted_vector}")
else:
    print(f"The word '{target_word}' is not in the model's vocabulary.")

from collections import Counter

word_counts = Counter(clean_corpus_tokens)

# the top 10 most common words (returns a list of tuples: [(word, freq), ...])
top_10_words = word_counts.most_common(10)

# Format the output exactly as requested: word1, freq1, word2, freq2, ...
formatted_output = ", ".join([f"{word}, {freq}" for word, freq in top_10_words])


print(formatted_output)

